// Keep this list aligned with Backend/src/config/canonicalFields.js
// so the import UI can only offer fields that the backend understands.
export const CANONICAL_FIELD_OPTIONS = [
  "active_day_count",
  "age_group",
  "age_years",
  "alcohol_weekday",
  "alcohol_weekend",
  "assessment_due_day",
  "assessment_id",
  "assessment_name",
  "assessment_order",
  "assessment_result_id",
  "assessment_type",
  "assessment_weight_pct",
  "absence_count",
  "course_duration_days",
  "course_id",
  "course_name",
  "course_run",
  "disability_flag",
  "engagement_count",
  "engagement_event_id",
  "enrollment_end_day",
  "enrollment_start_day",
  "event_day",
  "family_relation",
  "family_size",
  "family_support_flag",
  "father_education_level",
  "father_job",
  "final_outcome",
  "free_time",
  "gender",
  "go_out_freq",
  "guardian_type",
  "has_extracurricular",
  "has_paid_class",
  "has_romantic",
  "health_status",
  "highest_education",
  "higher_education_intent_flag",
  "imd_score_numeric",
  "internet_access_flag",
  "is_banked",
  "is_final_assessment",
  "mother_education_level",
  "mother_job",
  "parent_cohabitation_status",
  "pass_flag",
  "previous_attempt_count",
  "region",
  "residence_area",
  "resource_id",
  "resource_type",
  "school",
  "school_support_flag",
  "score_normalized",
  "socioeconomic_band",
  "source_dataset",
  "study_load_credits",
  "subject_area",
  "submission_day",
  "submission_delay_days",
  "student_id",
  "travel_time",
  "week_number"
];

export const TRANSFORM_OPTIONS = [
  "direct_copy",
  "ignore",
  "cast_int",
  "cast_float",
  "cast_boolean",
  "normalize_gender",
  "normalize_score",
  "convert_date_to_relative_day"
];

export const ENTITY_SCOPE_OPTIONS = [
  "student",
  "course",
  "assessment",
  "engagement_event",
  "system"
];

export const STATUS_OPTIONS = [
  "confirmed",
  "needs_review",
  "ignored",
  "suggested"
];
